name: CI/CD

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  # Job for running tests on develop branch
  test:
    if: github.event.pull_request.base.ref == 'develop' # Runs only for pull requests to the develop branch
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run tests
        uses: docker/build-push-action@v6
        with:
          target: test
          load: true

  # Job for building and pushing Docker image on main branch
  build_and_push:
    if: github.event.pull_request.base.ref == 'main' # Runs only for pull requests to the main branch
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64/v8
          push: true
          target: prod
          tags: yfakihi/jwt-auth-back:latest
